const plugin = require('tailwindcss/plugin');

module.exports = {
  purge: ['./pages/**/*.tsx', './components/**/*.tsx'],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['Poppins', 'ui-serif', 'Georgia', 'sans-serif'],
        mono: ['Poppins', 'ui-monospace', 'SFMono-Regular', 'sans-serif'],
        display: ['Poppins', 'sans-serif'],
        body: ['Poppins', 'sans-serif'],
      },
      colors: {
        gray: {
          50: '#F5F7FA',
          100: '#E4E7EB',
          200: '#CBD2D9',
          300: '#9AA5B1',
          400: '#7B8794',
          500: '#616E7C',
          600: '#52606D',
          700: '#3E4C59',
          800: '#323F4B',
          900: '#1F2933',
        },
        blue: {
          50: '#E3F8FF',
          100: '#B3ECFF',
          200: '#81DEFD',
          300: '#5ED0FA',
          400: '#40C3F7',
          500: '#2BB0ED',
          600: '#1992D4',
          700: '#127FBF',
          800: '#0B69A3',
          900: '#035388',
        },
      },
    },
  },
  variants: {
    extend: {
      padding: ['important'],
      backgroundColor: ['important'],
      accessibility: ['important'],
      alignContent: ['important'],
      alignItems: ['important'],
      alignSelf: ['important'],
      animation: ['important'],
      appearance: ['important'],
      backgroundAttachment: ['important'],
      backgroundClip: ['important'],
      backgroundImage: ['important'],
      backgroundOpacity: ['important'],
      backgroundPosition: ['important'],
      backgroundRepeat: ['important'],
      backgroundSize: ['important'],
      borderCollapse: ['important'],
      borderColor: ['important'],
      borderOpacity: ['important'],
      borderRadius: ['important'],
      borderStyle: ['important'],
      borderWidth: ['important'],
      boxShadow: ['important'],
      boxSizing: ['important'],
      clear: ['important'],
      container: ['important'],
      cursor: ['important'],
      display: ['important'],
      divideColor: ['important'],
      divideOpacity: ['important'],
      divideStyle: ['important'],
      divideWidth: ['important'],
      fill: ['important'],
      flex: ['important'],
      flexDirection: ['important'],
      flexGrow: ['important'],
      flexShrink: ['important'],
      flexWrap: ['important'],
      float: ['important'],
      fontFamily: ['important'],
      fontSize: ['important'],
      fontSmoothing: ['important'],
      fontStyle: ['important'],
      fontVariantNumeric: ['important'],
      fontWeight: ['important'],
      gap: ['important'],
      gradientColorStops: ['important'],
      gridAutoColumns: ['important'],
      gridAutoFlow: ['important'],
      gridAutoRows: ['important'],
      gridColumn: ['important'],
      gridColumnEnd: ['important'],
      gridColumnStart: ['important'],
      gridRow: ['important'],
      gridRowEnd: ['important'],
      gridRowStart: ['important'],
      gridTemplateColumns: ['important'],
      gridTemplateRows: ['important'],
      height: ['important'],
      inset: ['important'],
      justifyContent: ['important'],
      justifyItems: ['important'],
      justifySelf: ['important'],
      letterSpacing: ['important'],
      lineHeight: ['important'],
      listStylePosition: ['important'],
      listStyleType: ['important'],
      margin: ['important'],
      maxHeight: ['important'],
      maxWidth: ['important'],
      minHeight: ['important'],
      minWidth: ['important'],
      objectFit: ['important'],
      objectPosition: ['important'],
      opacity: ['important', 'disabled'],
      order: ['important'],
      outline: ['important'],
      overflow: ['important'],
      overscrollBehavior: ['important'],
      placeContent: ['important'],
      placeItems: ['important'],
      placeSelf: ['important'],
      placeholderColor: ['important'],
      placeholderOpacity: ['important'],
      pointerEvents: ['important'],
      position: ['important'],
      resize: ['important'],
      ringColor: ['important'],
      ringOffsetColor: ['important'],
      ringOffsetWidth: ['important'],
      ringOpacity: ['important'],
      ringWidth: ['important'],
      rotate: ['important'],
      scale: ['important'],
      skew: ['important'],
      space: ['important'],
      stroke: ['important'],
      strokeWidth: ['important'],
      tableLayout: ['important'],
      textAlign: ['important'],
      textColor: ['important'],
      textDecoration: ['important'],
      textOpacity: ['important'],
      textOverflow: ['important'],
      textTransform: ['important'],
      transform: ['important'],
      transformOrigin: ['important'],
      transitionDelay: ['important'],
      transitionDuration: ['important'],
      transitionProperty: ['important'],
      transitionTimingFunction: ['important'],
      translate: ['important'],
      userSelect: ['important'],
      verticalAlign: ['important'],
      visibility: ['important'],
      whitespace: ['important'],
      width: ['important'],
      wordBreak: ['important'],
      zIndex: ['important'],
    },
  },
  plugins: [
    plugin(function ({ addBase, theme }) {
      addBase({
        h1: { color: 'white' },
        h2: { color: 'white' },
        h3: { color: 'white' },
        h4: { color: 'white' },
        h5: { color: 'white' },
        h6: { color: 'white' },
        p: { color: 'white' },
        span: { color: 'white' },
        a: { color: 'white' },
      });
    }),
    plugin(function ({ addVariant }) {
      addVariant('important', ({ container }) => {
        container.walkRules(rule => {
          rule.selector = `.\\!${rule.selector.slice(1)}`;
          rule.walkDecls(decl => {
            decl.important = true;
          });
        });
      });
    }),
  ],
};
